FROM node:22.12.0

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the full application (including public folder)
COPY . .

# Ensure the container listens on all interfaces
ENV HOST=0.0.0.0
ENV PORT=5000

# Expose the port
EXPOSE 5000

# Run the app directly using Node or npm
CMD ["npm", "run", "start"]
